CREATE TABLE tenants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  active BOOLEAN NOT NULL,
  rate_per_second INTEGER NOT NULL,
  burst INTEGER NOT NULL,
  max_attempts INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE app_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL,
  role VARCHAR(30) NOT NULL,
  tenant_id BIGINT REFERENCES tenants(id)
);

CREATE TABLE channel_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  channel VARCHAR(20) NOT NULL,
  enabled BOOLEAN NOT NULL,
  sender_id VARCHAR(200),
  CONSTRAINT uq_channel_cfg UNIQUE (tenant_id, channel)
);

CREATE TABLE templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  name VARCHAR(100) NOT NULL,
  channel VARCHAR(20) NOT NULL,
  version INTEGER NOT NULL,
  subject VARCHAR(500),
  body VARCHAR(4000) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT uq_template_version UNIQUE (tenant_id, name, channel, version)
);

CREATE TABLE global_limits (
  id INTEGER PRIMARY KEY,
  rate_per_second INTEGER NOT NULL,
  burst INTEGER NOT NULL
);
INSERT INTO global_limits (id, rate_per_second, burst) VALUES (1, 1000, 2000);

CREATE TABLE notifications (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  channel VARCHAR(20) NOT NULL,
  template_id BIGINT NOT NULL REFERENCES templates(id),
  recipient VARCHAR(320) NOT NULL,
  subject VARCHAR(500),
  body VARCHAR(4000) NOT NULL,
  status VARCHAR(20) NOT NULL,
  idempotency_key VARCHAR(100),
  scheduled_at TIMESTAMP WITH TIME ZONE,
  next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
  attempt_count INTEGER NOT NULL,
  lease_until TIMESTAMP WITH TIME ZONE,
  last_error VARCHAR(1000),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL,
  CONSTRAINT uq_notification_idem UNIQUE (tenant_id, idempotency_key)
);
CREATE INDEX idx_notifications_due ON notifications (status, next_attempt_at);
CREATE INDEX idx_notifications_tenant ON notifications (tenant_id, created_at);

CREATE TABLE notification_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id VARCHAR(36) NOT NULL REFERENCES notifications(id),
  attempt_no INTEGER NOT NULL,
  outcome VARCHAR(20) NOT NULL,
  error VARCHAR(1000),
  started_at TIMESTAMP WITH TIME ZONE NOT NULL,
  finished_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE notification_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id VARCHAR(36) NOT NULL REFERENCES notifications(id),
  tenant_id BIGINT NOT NULL,
  from_status VARCHAR(20),
  to_status VARCHAR(20) NOT NULL,
  attempt_no INTEGER NOT NULL,
  reason VARCHAR(500),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_events_notification ON notification_events (notification_id);
